# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [(modulesPath + "/installer/scan/not-detected.nix")
];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/144036eb-53fb-47b9-b5c7-cee1bbe94ccd";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/33BD-B425";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/67135067-073b-4139-aa19-cb9875046679"; }
 ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Enable keyd remaps for laptop
  # Enable keyd for keyboard remapping
  services.keyd = {
    enable = true;
    keyboards = {
      default = {
        ids = [ "*" ]; # Applies to all attached keyboards
        settings = {
          main = {
            # You can put any base layer rebinds here if needed in the future
          };
          alt = {
            # The left side is the key pressed while Alt is held, the right is the output
            m = "backspace";
            "," = "enter"; # Punctuation keys must be wrapped in quotes in Nix
            "." = ";";
          };
        };
      };
    };
  };
}
